/* Populate database with sample data. */

INSERT INTO ANIMALS VALUES (1, 'Agumon', '2020-02-03', 0, TRUE, 10.23);
INSERT INTO ANIMALS VALUES (2, 'Gabumon', '2018-11-15', 2, TRUE, 8);
INSERT INTO ANIMALS VALUES (3, 'Pikachu', '2021-01-07', 1, FALSE, 15.04);
INSERT INTO ANIMALS VALUES (4, 'Devimon', '2017-05-12', 5, TRUE, 11);

/* Vet clinic database: query and update animals table */
INSERT INTO ANIMALS VALUES (5, 'Charmander', '2020-02-08', 0, FALSE, -11);
INSERT INTO ANIMALS VALUES (6, 'Plantmon', '2022-11-15', 2, TRUE, -5.7);
INSERT INTO ANIMALS VALUES (7, 'Squirtle', '1993-04-02', 3, FALSE, -12.13);
INSERT INTO ANIMALS VALUES (8, 'Angemon', '2005-06-12', 1, TRUE, -45);
INSERT INTO ANIMALS VALUES (9, 'Boarmon', '2005-06-07', 7, TRUE, 20.4);
INSERT INTO ANIMALS VALUES (10, 'Blossom', '1998-10-13', 3, TRUE, 17);


/* Vet clinic database: query multiple tables */

INSERT INTO OWNERS VALUES (1, 'Sam Smith', 34);
INSERT INTO OWNERS VALUES (2, 'Jennifer Orwell', 19);
INSERT INTO OWNERS VALUES (3, 'Bod', 45);
INSERT INTO OWNERS VALUES (4, 'Melody Pond', 77);
INSERT INTO OWNERS VALUES (5, 'Dean Winchester', 14);
INSERT INTO OWNERS VALUES (6, 'Jodie Whittaker', 38);


INSERT INTO SPECIES VALUES (1, 'Pokemon');
INSERT INTO SPECIES VALUES (2, 'Digimon');

UPDATE ANIMALS SET SPECIES_ID = 1;
UPDATE ANIMALS SET SPECIES_ID = 2 WHERE NAME LIKE '%mon';

UPDATE ANIMALS SET OWNER_ID=1  WHERE NAME='Agumon';
UPDATE ANIMALS SET OWNER_ID=2 WHERE NAME='Gabumon';
UPDATE ANIMALS SET OWNER_ID=2 WHERE NAME='Pikachu';
UPDATE ANIMALS SET OWNER_ID=3 WHERE NAME='Devimon';
UPDATE ANIMALS SET OWNER_ID=4 WHERE NAME='Charmander';
UPDATE ANIMALS SET OWNER_ID=4 WHERE NAME='Squirtle';
UPDATE ANIMALS SET OWNER_ID=4 WHERE NAME='Blossom';
UPDATE ANIMALS SET OWNER_ID=5 WHERE NAME='Angemon';
UPDATE ANIMALS SET OWNER_ID=5 WHERE NAME='Boarmon';

