/*Queries that provide answers to the questions from all projects.*/

SELECT * FROM ANIMALS WHERE NAME LIKE '%mon';
SELECT NAME FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '2016-01-01' AND '2019-01-01';
SELECT NAME FROM ANIMALS WHERE NEUTERED = TRUE AND ESCAPE_ATTEMPTS < 3;
SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME = 'Agumon' OR NAME = 'Pikachu';
SELECT NAME, ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT_KG > 10.5;
SELECT * FROM ANIMALS WHERE NEUTERED = TRUE;
SELECT * FROM ANIMALS WHERE NAME != 'Gabumon';
SELECT * FROM ANIMALS WHERE WEIGHT_KG BETWEEN 10.40 AND 17.30;

/* Vet clinic database: query and update animals table */
SELECT COUNT(*) FROM ANIMALS;
SELECT COUNT(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE ESCAPE_ATTEMPTS='0';
SELECT AVG(WEIGHT_KG) FROM ANIMALS;
SELECT NEUTERED, SUM(ESCAPE_ATTEMPTS) FROM ANIMALS GROUP BY NEUTERED;
SELECT SPECIES, MIN(WEIGHT_KG), MAX(WEIGHT_KG) FROM ANIMALS GROUP BY SPECIES;
SELECT DATE_OF_BIRTH, AVG(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '1990-01-01' AND '2000-01-01' GROUP BY DATE_OF_BIRTH;