/*Queries that provide answers to the questions from all projects.*/

SELECT * FROM ANIMALS WHERE NAME LIKE '%mon';
SELECT NAME FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '2016-01-01' AND '2019-01-01';
SELECT NAME FROM ANIMALS WHERE NEUTERED = TRUE AND ESCAPE_ATTEMPTS < 3;
SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME = 'Agumon' OR NAME = 'Pikachu';
SELECT NAME, ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT_KG > 10.5;
SELECT * FROM ANIMALS WHERE NEUTERED = TRUE;
SELECT * FROM ANIMALS WHERE NAME != 'Gabumon';
SELECT * FROM ANIMALS WHERE WEIGHT_KG BETWEEN 10.40 AND 17.30;

/* Vet clinic database: query and update animals table */

SELECT COUNT(*) FROM ANIMALS;
SELECT COUNT(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE ESCAPE_ATTEMPTS='0';
SELECT AVG(WEIGHT_KG) FROM ANIMALS;
SELECT NEUTERED, SUM(ESCAPE_ATTEMPTS) FROM ANIMALS GROUP BY NEUTERED;
SELECT SPECIES, MIN(WEIGHT_KG), MAX(WEIGHT_KG) FROM ANIMALS GROUP BY SPECIES;
SELECT DATE_OF_BIRTH, AVG(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '1990-01-01' AND '2000-01-01' GROUP BY DATE_OF_BIRTH;


/* Transactions 1 */

BEGIN;
UPDATE ANIMALS SET SPECIES = 'digimon' WHERE NAME LIKE '%mon';
UPDATE ANIMALS SET SPECIES = 'pokemon' WHERE SPECIES='';
COMMIT;


/* Transactions 2 */

BEGIN;
DELETE FROM ANIMALS;
ROLLBACK;


/* Transactions 3 */

BEGIN;
DELETE FROM ANIMALS WHERE DATE_OF_BIRTH>'2022-01-01';
SAVEPOINT SP1;
UPDATE ANIMALS SET WEIGHT_KG=WEIGHT_KG*(-1);
ROLLBACK TO SP1;
COMMIT;


/* Vet clinic database: query multiple tables */

SELECT FULL_NAME, NAME FROM ANIMALS A INNER JOIN OWNERS O ON A.OWNER_ID = O.ID WHERE O.FULL_NAME='Melody Pond';
SELECT A.NAME FROM ANIMALS A JOIN SPECIES S ON A.SPECIES_ID = S.ID WHERE A.SPECIES_ID=1;
SELECT FULL_NAME, NAME FROM OWNERS O LEFT JOIN ANIMALS A ON O.ID = A.OWNER_ID;
SELECT S.NAME, COUNT(SPECIES_ID) FROM ANIMALS A JOIN SPECIES S ON A.SPECIES_ID=S.ID GROUP BY S.NAME;
SELECT FULL_NAME, S.NAME FROM OWNERS O JOIN ANIMALS A ON O.ID=A.OWNER_ID JOIN SPECIES S ON S.ID=O.ID WHERE O.ID=2;
SELECT FULL_NAME, A.NAME FROM ANIMALS A JOIN OWNERS O ON A.OWNER_ID=O.ID WHERE escape_attempts=0 AND FULL_NAME='Dean Winchester';
SELECT full_name, COUNT(full_name) FROM (
SELECT full_name FROM animals LEFT JOIN owners ON owner_id = owners.id) AS count GROUP BY full_name HAVING COUNT (full_name) = 
(SELECT MAX(count) FROM 
(SELECT full_name, COUNT(full_name) FROM animals LEFT JOIN owners ON owner_id = owners.id GROUP BY full_name) AS count);
